version: 2.1
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            npm ci --prefix src/

jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - install_deps

workflows:
  build-and-packge:
    jobs:
      - ci-build

