version: 2.1
commands:
  install_deps:
    steps:
      - run:
          name: Install dependencies
          command: |
            npm ci --prefix src/

jobs:
  ci-build:
    docker:
      - image: circleci/node:lts
    environment:
      JEST_JUNIT_OUTPUT_DIR: test-output/
    steps:
      - checkout
      - install_deps
      - run:
          name: Run lint
          command: |
            npm run test-lint --prefix src/
      - run:
          name: Run unit tests
          command: |
            npm run test-unit --prefix src/
      - run:
          name: Validate Coverage
          command: |
            cd src/
            bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: src/test-output/
  
  sast:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Install NodeJsScan
          command: |
            sudo apt update
            sudo apt install python3-pip
            pip3 install nodejsscan
      - run:
          name: Execute Node Scan
          command: |
            nodejsscan -d ./src -o sast-output.json
      - store_artifacts:
          path: sast-output.json
      - run:
          name: Parse Sast Report
          command:
            exit $(cat sast-output.json | jq .total_count.sec)

  integration-test:
    docker:
      - image: circleci/node:lts
      - image: mongo:4.0
    environment:
      JEST_JUNIT_OUTPUT_DIR: test-output/
    steps:
      - checkout
      - install_deps
      - run:
          name: Run integration tests
          command:
            npm run test-integration --prefix src/
      - store_test_results:
          path: src/test-output/
  
  e2e-test:
    machine:
      image: circleci/classic:latest
    environment:
      QAW_HEADLESS: true
    steps: 
      - checkout
      - run:
          name: End 2 end tests
          no_output_timeout: 2m
          command: |
            chmod +x scripts/e2e-ci.sh
            ./scripts/e2e-ci.sh

  package:
    docker:
      - image: circleci/node:lts
    environment:
      NODE_ENV: production
    steps:
      - checkout
      - install_deps
      - run:
          name: Package
          command: |
            cd src
            npm pack
      - store_artifacts:
          path: ./src/simpletodoapp-1.0.0.tgz
          destionaion: ./simpletodoapp-1.0.0.tgz

workflows:
  build-and-packge:
    jobs:
      - ci-build
      - integration-test:
          requires:
            - ci-build
      - sast:
          requires:
            - ci-build
      - e2e-test:
          requires:
            - integration-test
            - ci-build
      - package:
          requires:
            - integration-test
            - sast
            - e2e-test
          filters:
            branches:
              only:
                - master
